apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
    app: {{ .Values.product }}
    tier: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.product }}
    tier: {{ .Values.appName }}
  ports:
  - name: {{ .Values.appName }}-service
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
