apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-{{ .Release.Namespace }}
  {{- if .Values.global.ingress.annotations }}
  annotations:
  {{ toYaml .Values.global.ingress.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ .Values.product }}
    tier: {{ .Values.appName }}
spec:
  rules:
    - host: {{ .Values.global.corezoid_dbcall.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}-service
                port:
                  number: 8080